# Generated by Django 4.1.7 on 2023-03-19 06:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_post_meta_description_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
